# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-12 19:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170412_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='codigoPedido',
            new_name='pedido',
        ),
        migrations.RenameField(
            model_name='itempedido',
            old_name='codigoProduto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='itemvenda',
            old_name='codigoProduto',
            new_name='produto',
        ),
        migrations.RenameField(
            model_name='itemvenda',
            old_name='codigoVenda',
            new_name='venda',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='codigoFornecedor',
            new_name='fornecedor',
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='codigoCliente',
            new_name='cliente',
        ),
    ]
